# Generated by Django 5.0.6 on 2024-05-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("song", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="song",
            table="songs",
        ),
    ]
