# Generated by Django 5.0.6 on 2024-05-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("song", "0002_alter_song_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="genre",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="song",
            name="image",
            field=models.CharField(
                default="https://via.placeholder.com/300", max_length=50
            ),
        ),
    ]
