# Generated by Django 5.0.6 on 2024-05-21 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_is_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stagename", models.CharField(max_length=50, unique=True)),
                ("dob", models.DateField(null=True)),
                ("gender", models.CharField(default="male", max_length=10)),
                ("nationality", models.CharField(max_length=50, null=True)),
                (
                    "artist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_detail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
