# Generated by Django 5.0.6 on 2024-05-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_artistdetails"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="artistdetails",
            table="artist_details",
        ),
    ]
