# Generated by Django 5.0.6 on 2024-05-21 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_rename_artistdetails_artistdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistdetail",
            name="artist",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
