# Generated by Django 5.0.6 on 2024-05-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_artistdetail_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistdetail",
            name="stagename",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
