# Generated by Django 5.0.6 on 2024-05-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_artistdetail_stagename"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistdetail",
            name="description",
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="artistdetail",
            name="facebook_link",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="artistdetail",
            name="instagram_link",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="artistdetail",
            name="twitter_link",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.CharField(
                default="https://via.placeholder.com/150", max_length=50
            ),
        ),
    ]
