# Generated by Django 5.0.6 on 2024-05-23 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_artistdetail_description_artistdetail_facebook_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artistdetail",
            old_name="description",
            new_name="biography",
        ),
    ]
